env: "local"
state-ttl: 10m
grpc:
  host: "0.0.0.0"
  port: 49104
psql:
  host: "localhost"
  port: 49105
  user: "root"
  password: "1234"
  db: "schedule"
redis:
  host: "localhost"
  port: 6380
  pass: "1234"
google-calendar:
  redirect-url: "http://localhost:49106/loginCallback"
redpanda:
  brokers:
    - "localhost:9092"
  topics:
    - "schedule.schedule.created"
  group_id: "schedule"
